module ActiveWarehouse
  module View
    # A view that can figure out the SQL used by a report, rather than
    # the results generated by executing that SQL.  Useful if you want
    # to allow users to copy the SQL and manipulate it in another more
    # general SQL interface to your datawarehouse.
    class SqlView
      include AbstractView
      # Returns the SQL for the query.
      def sql
        report.cube.query_row_and_column(row_dimension, column_dimension, 
          :conditions => report.conditions, 
          :return => :sql )
      end
    end
  end
end