# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "activewarehouse_schema_info", :id => false, :force => true do |t|
    t.column "version", :integer
  end

  create_table "author_dimension", :force => true do |t|
    t.column "name", :string
  end

  add_index "author_dimension", ["name"], :name => "index_author_dimension_on_name"

  create_table "change_type_dimension", :force => true do |t|
    t.column "change_type_code",        :string
    t.column "change_type_description", :string
  end

  add_index "change_type_dimension", ["change_type_code"], :name => "index_change_type_dimension_on_change_type_code"
  add_index "change_type_dimension", ["change_type_description"], :name => "index_change_type_dimension_on_change_type_description"

  create_table "date_dimension", :force => true do |t|
    t.column "calendar_quarter",              :string
    t.column "calendar_week",                 :string
    t.column "day_of_week",                   :string
    t.column "calendar_week_number_in_year",  :integer
    t.column "calendar_year_quarter",         :string
    t.column "day_number_in_calendar_month",  :integer
    t.column "calendar_month_name",           :string
    t.column "date",                          :string
    t.column "major_event",                   :string
    t.column "calendar_year",                 :string
    t.column "day_number_in_calendar_year",   :integer
    t.column "calendar_month_number_in_year", :integer
    t.column "sql_date_stamp",                :date
    t.column "calendar_year_month",           :string
    t.column "calendar_week_ending_date",     :string
  end

  add_index "date_dimension", ["calendar_quarter"], :name => "index_date_dimension_on_calendar_quarter"
  add_index "date_dimension", ["calendar_week"], :name => "index_date_dimension_on_calendar_week"
  add_index "date_dimension", ["day_of_week"], :name => "index_date_dimension_on_day_of_week"
  add_index "date_dimension", ["calendar_week_number_in_year"], :name => "index_date_dimension_on_calendar_week_number_in_year"
  add_index "date_dimension", ["calendar_year_quarter"], :name => "index_date_dimension_on_calendar_year_quarter"
  add_index "date_dimension", ["day_number_in_calendar_month"], :name => "index_date_dimension_on_day_number_in_calendar_month"
  add_index "date_dimension", ["calendar_month_name"], :name => "index_date_dimension_on_calendar_month_name"
  add_index "date_dimension", ["date"], :name => "index_date_dimension_on_date"
  add_index "date_dimension", ["major_event"], :name => "index_date_dimension_on_major_event"
  add_index "date_dimension", ["calendar_year"], :name => "index_date_dimension_on_calendar_year"
  add_index "date_dimension", ["day_number_in_calendar_year"], :name => "index_date_dimension_on_day_number_in_calendar_year"
  add_index "date_dimension", ["calendar_month_number_in_year"], :name => "index_date_dimension_on_calendar_month_number_in_year"
  add_index "date_dimension", ["sql_date_stamp"], :name => "index_date_dimension_on_sql_date_stamp"
  add_index "date_dimension", ["calendar_year_month"], :name => "index_date_dimension_on_calendar_year_month"
  add_index "date_dimension", ["calendar_week_ending_date"], :name => "index_date_dimension_on_calendar_week_ending_date"

  create_table "file_dimension", :force => true do |t|
    t.column "file_type", :string
    t.column "framework", :string
    t.column "path",      :string
    t.column "directory", :string
    t.column "extension", :string
    t.column "file_base", :string
    t.column "file_name", :string
  end

  add_index "file_dimension", ["file_type"], :name => "index_file_dimension_on_file_type"
  add_index "file_dimension", ["framework"], :name => "index_file_dimension_on_framework"
  add_index "file_dimension", ["path"], :name => "index_file_dimension_on_path"
  add_index "file_dimension", ["directory"], :name => "index_file_dimension_on_directory"
  add_index "file_dimension", ["extension"], :name => "index_file_dimension_on_extension"
  add_index "file_dimension", ["file_base"], :name => "index_file_dimension_on_file_base"
  add_index "file_dimension", ["file_name"], :name => "index_file_dimension_on_file_name"

  create_table "file_revision_facts", :force => true do |t|
    t.column "date_id",        :integer,                 :null => false
    t.column "file_id",        :integer,                 :null => false
    t.column "change_type_id", :integer,                 :null => false
    t.column "author_id",      :integer,                 :null => false
    t.column "revision",       :string,  :default => "", :null => false
    t.column "file_changed",   :integer, :default => 1
  end

  add_index "file_revision_facts", ["date_id"], :name => "index_file_revision_facts_on_date_id"
  add_index "file_revision_facts", ["file_id"], :name => "index_file_revision_facts_on_file_id"
  add_index "file_revision_facts", ["change_type_id"], :name => "index_file_revision_facts_on_change_type_id"
  add_index "file_revision_facts", ["author_id"], :name => "index_file_revision_facts_on_author_id"

  create_table "table_reports", :force => true do |t|
    t.column "title",                 :string
    t.column "cube_name",             :string,   :default => "", :null => false
    t.column "column_dimension_name", :string
    t.column "column_hierarchy",      :string
    t.column "column_constraints",    :text
    t.column "column_stage",          :integer
    t.column "column_param_prefix",   :string
    t.column "row_dimension_name",    :string
    t.column "row_hierarchy",         :string
    t.column "row_constraints",       :text
    t.column "row_stage",             :integer
    t.column "row_param_prefix",      :string
    t.column "fact_attributes",       :text
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
  end

end
